version: 2.0

jobs:
  "go-1.10":
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/utahta/go-validator
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test

  "go-1.11":
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/utahta/go-validator
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  build:
    jobs:
      - "go-1.10"
      - "go-1.11"
